cutoff_len: 2048
dataloader_num_workers: 4
dataset: huatuo_medical
do_train: true
eval_steps: 500
eval_strategy: steps
finetuning_type: lora
fp16: true
gradient_accumulation_steps: 4
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0.1
lora_rank: 8
lr_scheduler_type: cosine

model_name_or_path: /root/zhikangyun/model/models/Qwen--Qwen2.5-7B-Instruct/snapshots/master
output_dir: /root/zhikangyun/output
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 500
stage: sft
template: qwen
val_size: 0.1
warmup_steps: 100
